import { Uri } from 'vscode';

/**
 * Identifies which subsystem initiated the scan request.
 * Used for telemetry, logging, and priority computation.
 */
export type ScanSource =
  | 'autoscan'
  | 'startup'
  | 'manual'
  | 'config-change'
  | 'realtime';

/**
 * Priority tiers for scan jobs. Higher values execute first.
 * Tiers mirror the provider priority system but add event-type granularity.
 */
export enum ScanPriority {
  /** Explicit user action (Scan Workspace button, manual refresh) */
  Manual = 100,
  /** Config change re-enabling a provider */
  ConfigChange = 90,
  /** Extension startup scan */
  Startup = 80,
  /** File save — primary auto-scan trigger */
  Save = 50,
  /** File create/rename — may introduce new problems */
  Create = 40,
  /** File rename — old URI needs clearing, new URI needs scan */
  Rename = 35,
  /** File delete — clear ownership/stale badges */
  Delete = 30,
  /** Realtime diagnostics from language server */
  Realtime = 20,
  /** Periodic reconciliation / stale badge cleanup */
  Reconcile = 10,
}

/**
 * A single unit of scan work routed through the ScanScheduler.
 *
 * Encapsulates everything the scheduler needs to make ordering, deduplication,
 * and cancellation decisions without inspecting provider internals.
 */
export interface ScanJob {
  /** Stable provider id (matches descriptor.id / provider.name). */
  readonly provider: string;
  /** Human-readable reason for the scan (for logs/telemetry). */
  readonly reason: string;
  /** The specific file(s) that triggered this job. Empty = full workspace. */
  readonly uris: readonly Uri[];
  /** Execution priority — higher runs first. Derived from event type + provider priority. */
  readonly priority: number;
  /** Monotonic timestamp when the job was created (Date.now()). */
  readonly timestamp: number;
  /** Optional AbortSignal for cooperative cancellation. */
  readonly signal?: AbortSignal;
  /** Unique id for tracing (generated by scheduler on submit). */
  readonly jobId: string;
}

/**
 * (R3) Fine-grained file‑event discriminator. Used together with {@link ScanJobRequest.source}
 * to compute priority. `save` outranks `rename` outranks `delete` outranks
 * `create` (per the design brief's priority ladder), all above realtime and reconcile.
 *
 * `reconcile` is wired in R4. `other` covers non‑file events (manual, startup,
 * config‑change) where the source alone determines tier.
 */
export type ScanEventKind =
  | 'save'
  | 'create'
  | 'rename'
  | 'delete'
  | 'reconcile'
  | 'other';

/**
 * Request payload for submitting a scan job to the scheduler.
 * The scheduler enriches this with timestamp, jobId, and priority.
 */
export interface ScanJobRequest {
  /** Provider ids to scan. Must match descriptor.id / provider.name. */
  readonly providerNames: readonly string[];
  /** Human-readable reason for the scan (for logs/telemetry). */
  readonly reason: string;
  /** Source subsystem (for telemetry). */
  readonly source: 'autoscan' | 'startup' | 'manual' | 'config-change' | 'realtime' | 'reconcile';
  /** (R3) Fine-grained file‑event discriminator. Defaults to 'other'. */
  readonly event?: ScanEventKind;
  /** Specific file(s) that triggered this request. Empty = full workspace. */
  readonly uris?: readonly Uri[];
  /** Optional override — otherwise computed from event type + provider priority. */
  readonly priority?: number;
  /** Optional AbortSignal for cooperative cancellation. */
  readonly signal?: AbortSignal;
}

/**
 * Result of submitting a job to the scheduler.
 */
export interface ScanJobResult {
  /** Whether the job was accepted for execution. */
  readonly submitted: boolean;
  /** The provider(s) that will be scanned. */
  readonly providerNames: readonly string[];
  /** Original request reason. */
  readonly reason: string;
  /** Source subsystem. */
  readonly source: ScanJobRequest['source'];
  /** The created job (if submitted). */
  readonly job?: ScanJob;
  /** Why the job was not submitted (if submitted === false). */
  readonly skipReason?: string;
}

/**
 * Helper to compute priority from event source and provider base priority.
 * Provider priority (0-10) is in the ones place; event tier is tens/hundreds.
 */
export function computeScanPriority(
  eventTier: ScanPriority,
  providerBasePriority: number,
): number {
  return eventTier + Math.max(0, Math.min(9, providerBasePriority));
}

/**
 * Generate a compact job id for tracing.
 */
export function generateJobId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Explicit decision codes for scan routing. Every silent exit in the
 * routing pipeline returns one of these instead of a bare `return`,
 * so logs and debugging tools can show exactly why a scan was rejected.
 */
export enum ScanDecision {
  /** Job accepted and queued. */
  Accepted = 'accepted',
  /** Global autoScan feature flag is off. */
  GlobalDisabled = 'global_disabled',
  /** Provider is disabled in config. */
  ProviderDisabled = 'provider_disabled',
  /** Provider's autoScan config gate is off. */
  AutoScanDisabled = 'autoScan_disabled',
  /** No provider owns this file extension. */
  UnsupportedExtension = 'unsupported_extension',
  /** File has no extension. */
  NoExtension = 'no_extension',
  /** Provider list was empty. */
  NoProviders = 'no_providers',
  /** Provider is already scanning (pending refresh set). */
  ProviderBusy = 'provider_busy',
  /** Job was merged into an existing pending job (dedup). */
  Merged = 'merged',
}